### ISSUE TITLE
Namespace directives

### ISSUE THREAD

**Issue by ThomasBurleson** [rpocklin/angular-timeline#7]
I recommend you namespace your directives and CSS:
-  The reduces potential conflicts with other libraries
-  This helps identify your own library components/directives

``` js
angular.module('angular-timeline').directive('rp-timeline', function() {... }
angular.module('angular-timeline').directive('rp-timeline-panel', function() { ... }
```

> Note the additional hypens in `np-timeline-panel`

``` css
.rp-timeline {
  list-style: none;
  padding: 20px 0 20px;
  position: relative; 
}
```
